name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main
      - ci

jobs:
  deploy:
    name: Deploy to Firebase
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 22

    - name: Install Firebase CLI
      run: npm install -g firebase-tools

    - name: Authenticate with Firebase
      env:
        FIREBASE_SERVICE_ACCOUNT_KEY: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_KEY }}
      run: |
        echo "${FIREBASE_SERVICE_ACCOUNT_KEY}" > firebase-key.json
        firebase use --add ${{ secrets.FIREBASE_PROJECT_ID }} --token "$(cat firebase-key.json | jq -r .token)"
        rm firebase-key.json

    - name: Deploy to Firebase
      env:
        FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
      run: |
        firebase deploy --project $FIREBASE_PROJECT_ID --non-interactive
